drop table CUSTOMER cascade constraints ;
drop table CUSTOMER_INFO cascade constraints ;
drop table DISTRIBUTOR_CUSTOMER cascade constraints ;
drop table ETL_CUSTOMER cascade constraints ;
drop table ETL_CUSTOMER_TOT cascade constraints ;
drop table ETL_FILE cascade constraints ;
drop table ETL_INVENTORY cascade constraints ;
drop table ETL_INVENTORY_TOT cascade constraints ;
drop table ETL_SALE cascade constraints ;
drop table ETL_SALE_TOT cascade constraints ;
drop table ORG cascade constraints ;
drop table ORG_CUSTOMER cascade constraints ;
drop table ORG_DATAFEED cascade constraints ;
drop table ORG_DISTRIB cascade constraints ;
drop table ORG_MFR cascade constraints ;
drop table POST_SALE cascade constraints ;
drop table PRODUCT cascade constraints ;
drop table PRODUCT_NOMEN cascade constraints ;
drop table PRODUCT_PKG cascade constraints ;
drop table PRODUCT_SUSPECT_DTL cascade constraints ;
drop table PRODUCT_SUSPECT_HDR cascade constraints ;
drop table VALIDATED_ADDRESS cascade constraints ;
drop sequence CUSTOMER_ID_SEQ ;
drop sequence CUSTOMER_INFO_ID_SEQ ;
drop sequence DISTRIBUTOR_CUSTOMER_ID_SEQ ;
drop sequence ETL_CUSTOMER_ID_SEQ ;
drop sequence ETL_CUSTOMER_TOT_ID_SEQ ;
drop sequence ETL_FILE_ID_SEQ ;
drop sequence ETL_INVENTORY_ID_SEQ ;
drop sequence ETL_INVENTORY_TOT_ID_SEQ ;
drop sequence ETL_SALE_ID_SEQ ;
drop sequence ETL_SALE_TOT_ID_SEQ ;
drop sequence ORG_CUSTOMER_ID_SEQ ;
drop sequence ORG_DATAFEED_ID_SEQ ;
drop sequence ORG_DISTRIB_ID_SEQ ;
drop sequence ORG_ID_SEQ ;
drop sequence ORG_MFR_ID_SEQ ;
drop sequence POST_SALE_ID_SEQ ;
drop sequence PRODUCT_ID_SEQ ;
drop sequence PRODUCT_NOMEN_ID_SEQ ;
drop sequence PRODUCT_PKG_ID_SEQ ;
drop sequence PRODUCT_SUSPECT_DTL_ID_SEQ ;
drop sequence PRODUCT_SUSPECT_HDR_ID_SEQ ;
drop sequence VALIDATED_ADDRESS_ID_SEQ ;
drop view ETL_CUSTOMER_STAT ; 
drop view ETL_FILE_STAT ; 
drop view ETL_POST_SALE_STAT ; 
drop view ETL_SALE_POST_STATS ; 
drop view ETL_SALE_STAT ; 
drop view ETL_SALE_UNKNOWN_ITEM ; 
drop view LOAD_CONDITIONS ; 
drop view PRODUCT_VW ; 
drop view SALE_PRODUCT_CUST_VW ; 
drop package logger ;
